# Generated by Django 6.0.2 on 2026-02-18 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices='')),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(verbose_name=datetime.datetime(2026, 2, 18, 6, 5, 32, 52903, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
