# Generated by Django 6.0.2 on 2026-02-18 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 2, 18, 6, 8, 7, 54682, tzinfo=datetime.timezone.utc)),
        ),
    ]
