# Generated by Django 6.0.3 on 2026-03-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='CUSTOMER'),
        ),
    ]
