# Generated by Django 6.0.2 on 2026-03-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_signupmodel_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
