# Generated by Django 6.0.2 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_signupmodel_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='customer'),
        ),
    ]
