# Generated by Django 6.0.2 on 2026-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=450, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=450, unique=True), unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), unique=True),
        ),
    ]
