# Generated by Django 6.0.2 on 2026-02-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_category_title_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unit_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
