# Generated by Django 6.0.2 on 2026-02-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='unit_price',
        ),
    ]
