# Generated by Django 6.0.3 on 2026-04-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinformation',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productorder'),
        ),
    ]
