# Generated by Django 6.0.3 on 2026-03-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('discount_price', models.PositiveIntegerField(default=3)),
                ('vat_rate', models.PositiveIntegerField(default=13)),
                ('customer_type', models.CharField(choices=[('REGULAR', 'regular'), ('NORMAL', 'normal')], default='nomral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productorder')),
            ],
        ),
    ]
