# Generated by Django 6.0.3 on 2026-03-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_billingorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingorder',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='billingorder',
            name='vat_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
