# Generated by Django 6.0.3 on 2026-05-08 06:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_deliveryinformation_zip_alter_commentproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, null=True, region=None, unique=True),
        ),
    ]
