# Generated by Django 6.0.3 on 2026-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
