# Generated by Django 6.0.3 on 2026-03-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_billingorder_vat_rate_billingorder_vat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productorder'),
        ),
    ]
