# Generated by Django 6.0.3 on 2026-05-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_cartmodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.deliveryinformation'),
        ),
    ]
