# Generated by Django 6.0.3 on 2026-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_productorder_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinformation',
            name='phone_number',
        ),
    ]
