# Generated by Django 6.0.2 on 2026-02-18 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_signupmodel_options_alter_signupmodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
