# Generated by Django 6.0.3 on 2026-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_mydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_per',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
